# Generated by Django 3.1.2 on 2020-11-11 15:39

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60, verbose_name='نام محصول')),
                ('product_id', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(help_text='product description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=shopping.models.path_and_rename, verbose_name='تصویر')),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=13, verbose_name='قیمت')),
            ],
        ),
    ]
