# Generated by Django 3.1.2 on 2020-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20201111_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
