# Generated by Django 3.1.2 on 2020-11-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shopping', '0004_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.IntegerField(choices=[(1, 'مذهبی'), (2, 'رمان'), (3, 'درسی')], default='0',
                                      verbose_name='دسته بندی'),
        ),
    ]
