# Generated by Django 3.1.2 on 2020-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20201111_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.IntegerField(choices=[(1, 'مذهبی'), (2, 'رمان'), (3, 'درسی'), (4, 'علمی'), (0, 'null')], default=1, verbose_name='دسته بندی'),
        ),
    ]
