# Generated by Django 3.1.2 on 2020-11-12 09:55

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20201111_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='نام کتاب')),
                ('description', models.TextField(blank=True, help_text='product description', null=True, verbose_name='توضیحات')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=shopping.models.path_and_rename, verbose_name='تصویر')),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=13, verbose_name='قیمت')),
                ('genre', models.IntegerField(blank=True, choices=[(1, 'مذهبی'), (2, 'رمان'), (3, 'درسی'), (4, 'علمی')], default=None, verbose_name='دسته بندی')),
                ('condition', models.BooleanField(choices=[(0, 'موجود'), (1, 'نا موجود')], verbose_name='وضعیت')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
