# Generated by Django 3.1.2 on 2020-11-12 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20201112_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(null=False, blank=False, max_length=120, verbose_name='ناشر'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
    ]
